keys:
  - &orcas age10hlyqu583xc8z6xfjvte3y5ynquc3gf5rt8ammu67g3xgjy6feqssxeqvj
  - &cygnus age1cfjl885ntyphgyyg8jnm5dkz9x0am5s5r0npyf7f056fcr76tp9q3sfhsq
  - &aquarius age1z2vnk0tvjtsffjwhq7saem5pgapq9wfrwgxeneyn34kzyjhn7y3qtdz4q7
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *orcas
      - *cygnus
      - *aquarius
