keys:
  - &orcas age10hlyqu583xc8z6xfjvte3y5ynquc3gf5rt8ammu67g3xgjy6feqssxeqvj
  - &cygnus age13mje3ex03kr5dpqnh3p2ajavz23mwkd7d859q97zdnxal5za947sle0ews
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *orcas
      - *cygnus
